title: birmingHack 
description: The University of Birmingham's premier hackathon
url: birminghack.com

menu:
  - name: Archive
    link: /archive/2026
    children:
      - name: 2026
        link: /archive/2026/
      - name: 2025
        link: /archive/2025/
  - name: Schedule
    link: /#schedule
  - name: Sponsors
    link: /#sponsors
  - name: Partners
    link: /#partners
  - name: FAQs
    link: /#faqs
  - name: Tickets
    link: /#tickets

include: ["_redirects"]
keep_files: ["_redirects"]

